# Generated by Django 5.2.17 on 2026-08-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                ("resolved_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("quick", "Quick Scan"),
                            ("common", "Common Ports"),
                            ("full", "Full Scan"),
                            ("custom", "Custom Range"),
                            ("vuln", "Vulnerability Scan"),
                            ("stealth", "Stealth Scan"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("port_range_start", models.IntegerField(default=1)),
                ("port_range_end", models.IntegerField(default=1024)),
                ("custom_ports", models.CharField(blank=True, max_length=500)),
                ("timeout", models.FloatField(default=1.0)),
                ("threads", models.IntegerField(default=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("open_ports_count", models.IntegerField(default=0)),
                ("closed_ports_count", models.IntegerField(default=0)),
                ("filtered_ports_count", models.IntegerField(default=0)),
                ("risk_score", models.FloatField(default=0.0)),
                ("os_guess", models.CharField(blank=True, max_length=200)),
                ("whois_data", models.TextField(blank=True)),
                ("dns_info", models.TextField(blank=True)),
                ("geo_info", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                (
                    "protocol",
                    models.CharField(
                        choices=[("tcp", "TCP"), ("udp", "UDP")],
                        default="tcp",
                        max_length=5,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("filtered", "Filtered"),
                            ("open|filtered", "Open|Filtered"),
                        ],
                        max_length=15,
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=200)),
                ("banner", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("risk_notes", models.TextField(blank=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("http_title", models.CharField(blank=True, max_length=300)),
                ("http_headers", models.TextField(blank=True)),
                ("ssl_info", models.TextField(blank=True)),
                ("cve_hints", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="scanner.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["port"],
                "unique_together": {("session", "port", "protocol")},
            },
        ),
    ]
